var jsPsychAudioSurveyInputResponse = (function (jspsych) {
  'use strict';

  const info = {
      name: "audio-survey-input-response",
      parameters: {
          /** The audio file to be played. */
          /** NB in this experiment we have four audios to play, so we need to to do some coding here too */
          stimulus: {
              type: jspsych.ParameterType.STRING,
              pretty_name: "Stimulus",
              default: undefined,
          },
          /** Any content here will be displayed below the stimulus. */
          /** This used to be prompt but we've changed it */
          preamble: {
              type: jspsych.ParameterType.HTML_STRING,
              pretty_name: "Preamble",
              default: null,
          },
          /** HTML formatted string containing all the input elements to display. Every element has to have its own distinctive name attribute. The <form> tag must not be included and is generated by the plugin. */
          html: {
            type: jspsych.ParameterType.HTML_STRING,
            pretty_name: "HTML",
            default: null,
        },
          /** If true, then responses are allowed while the audio is playing. If false, then the audio must finish playing before a response is accepted. */
          response_allowed_while_playing: {
              type: jspsych.ParameterType.BOOL,
              pretty_name: "Response allowed while playing",
              default: true,
          },
          /** The text that appears on the button to finish the trial. */
          button_label: {
            type: jspsych.ParameterType.STRING,
            pretty_name: "Button label",
            default: "Continue",
        },
          /** If true, then the trial will end as soon as the audio file finishes playing. */
          trial_ends_after_audio: {
            type: jspsych.ParameterType.BOOL,
            pretty_name: "Trial ends after audio",
            default: false,
        },
      },
      
  };
  /**
   * **audio-survey-input-response**
   *
   * jsPsych plugin for playing an audio file and getting user input via an HTML form
   * A combination of the AudioKeyboardResponse and SurveyHtmlForm
   *
   * @author Josh de Leeuw
   * @see {@link https://www.jspsych.org/plugins/jspsych-audio-keyboard-response/ audio-keyboard-response plugin documentation on jspsych.org}
   * The new elements that we have added are the button and DataAsArray
   * We have changed prompt to preamble
   */
    
  class AudioSurveyInputResponsePlugin {
      constructor(jsPsych) {
          this.jsPsych = jsPsych;
      }
      trial(display_element, trial, on_load) {
        // hold the .resolve() function from the Promise that ends the trial
          let trial_complete;
          // setup stimulus
          var context = this.jsPsych.pluginAPI.audioContext();
          // store response
          var response = {
            rt: null,
            button: null,
        };
          // record webaudio context start time
          var startTime;
          // load audio file
          const setupTrial = () => {
            
            // enable buttons after audio ends if necessary
            if (!trial.response_allowed_while_playing) {
                this.audio.addEventListener("ended", enable_buttons);
            }
            var html = "";
            var buttons = trial.button_label
            // show text for user imput
            if (trial.preamble !== null) {
                html +='<div id="jspsych-audio-survey-input-response-preamble" class="jspsych-survey-html-form-preamble">' +trial.preamble + "</div>";
            }
            html += '<form id="jspsych-survey-html-form" autocomplete="off">';
            // add form HTML / input elements
            html += trial.html;
            // add submit button
            html += '<input type="submit" id="jspsych-survey-html-form-next" class="jspsych-btn jspsych-survey-html-form bet-button" disabled value="' +
              trial.button_label +
              '"></input>';
            html += "</form>";
            display_element.innerHTML = html;
            playAll(trial.stimulus);
           // end trial if time limit is set
           if (trial.trial_duration !== null) {
            this.jsPsych.pluginAPI.setTimeout(() => {
                end_trial();
            }, trial.trial_duration);
        } 
        on_load();
        };
          this.jsPsych.pluginAPI
              setupTrial();

          const enable_buttons = () => {
            var btns = document.querySelectorAll(".bet-button");
            var btn_el = btns[0];
                if (btn_el) {
                    btn_el.disabled = false;
                
        }
        };

        function playAll(audios) {
            var audioarray = audios.split(',');
            for (var i = 0; i < audioarray.length; i++) {
                var audio = document.getElementById(audioarray[i]);
                audio.play();
                while (!audio.ended) {
                }
            }
        }
        

        const fix_trial = ()=>{
            var html = "";
            var buttons = trial.button_label
            // show text for user imput
            if (trial.preamble !== null) {
                html +='<div id="jspsych-audio-survey-input-response-preamble" class="jspsych-survey-html-form-preamble">' +trial.preamble + "</div>";
            }
            html += '<form id="jspsych-survey-html-form" autocomplete="off">';
            // add form HTML / input elements
            html += trial.html;
            // add submit button
            html += '<input type="submit" id="jspsych-survey-html-form-next" class="jspsych-btn jspsych-survey-html-form bet-button" disabled value="' +
              trial.button_label +
              '"></input>';
            html += "</form>";
            display_element.innerHTML = html;
        };

        const end_trial = () => {
             // kill any remaining setTimeout handlers
             this.jsPsych.pluginAPI.clearAllTimeouts();
             this.audio.removeEventListener("ended", end_trial);
             display_element  
                .querySelector("#jspsych-survey-html-form")
                .addEventListener("submit", (event) => {
                    // measure response time
                    event.preventDefault();
                    var endTime = performance.now();
                    var response_time = Math.round(endTime - startTime);
                    var this_form = display_element.querySelector("#jspsych-survey-html-form");
                    
                    var question_data = serializeArray(this_form);
                    if (!trial.dataAsArray) {
                        question_data = objectifyForm(question_data);
                    }
                    // save data
                    var trialdata = {
                        rt: response_time,
                        response: question_data
                    }

                    display_element.innerHTML = "";
                    // next trial
                    this.jsPsych.finishTrial(trialdata);
                    trial_complete()
                    });
      };
      function serializeArray(form) {
        // Setup our serialized data
        var serialized = [];
        // Loop through each field in the form
        for (var i = 0; i < form.elements.length; i++) {
            var field = form.elements[i];
            // Don't serialize fields without a name, submits, buttons, file and reset inputs, and disabled fields
            if (!field.name ||
                field.disabled ||
                field.type === "file" ||
                field.type === "reset" ||
                field.type === "submit" ||
                field.type === "button")
                continue;
            // If a multi-select, get all selections
            if (field.type === "select-multiple") {
                for (var n = 0; n < field.options.length; n++) {
                    if (!field.options[n].selected)
                        continue;
                    serialized.push({
                        name: field.name,
                        value: field.options[n].value,
                    });
                }
            }
            // Convert field data to a query string
            else if ((field.type !== "checkbox" && field.type !== "radio") || field.checked) {
                serialized.push({
                    name: field.name,
                    value: field.value,
                });
            }
        }
        return serialized;
    }
    function objectifyForm(formArray) {
        //serialize data function
        var returnArray = {};
        for (var i = 0; i < formArray.length; i++) {
            returnArray[formArray[i]["name"]] = formArray[i]["value"];
        }
        return returnArray;
    }
    return new Promise((resolve) => {
        trial_complete = resolve;
    });
    }
    }
  AudioSurveyInputResponsePlugin.info = info;

  return AudioSurveyInputResponsePlugin;
  
})(jsPsychModule);
